---
- name: set up local dir with packer json and build files
  hosts: localhost
  gather_facts: no
  vars:
    man_packer_setup_version: 1

    ansible_user: white
    ansible_password: "password"

    opt_packer_setup_headless: false
    packer_builder: vsphere

  pre_tasks:
  - name: check that the Ansible version is at least 2.7
    assert:
      that:
      - ansible_version.major >= 2
      - ansible_version.minor >= 7
      msg: packer-windoze requires Ansible 2.7 or newer to run

  - name: check that the provider is valid
    assert:
      that:
      - packer_builder in ['vsphere']
      msg: packer-windoze does not support this builder

  - name: Process VMware vSphere based VM tasks
    include_tasks: config/read_vmware_config.yaml
    when: packer_builder == "vsphere"


  roles:
  - packer-setup

  post_tasks:
  - name: Export variables for provisioning phase
    copy:
      dest: "{{man_host_type}}/pri_packer_setup_config.yaml"
      content: "{{ pri_packer_setup_config | to_nice_yaml }}"
