---
- name: run ngen to recompile .NET assemblies
  win_dotnet_ngen:
  tags:
    ngen

- name: remove page file
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\Session Manager\Memory Management
    name: PagingFiles
    data: ""
    state: present
  register: pri_cleanup_pagefile_removal

- name: reboot server after clearing page file
  win_reboot:
  when: pri_cleanup_pagefile_removal is changed

- name: set flag to recreate pagefile after next sysprep
  win_shell: |
    $system = Get-WmiObject -Class Win32_ComputerSystem -EnableAllPrivileges
    if ($system -ne $null) {
        $system.AutomaticManagedPagefile = $true
        $system.Put()
    }

- name: cleanup the temp folders
  win_file:
    path: '{{ item }}'
    state: absent
  ignore_errors: yes  # doesn't matter too much if these fail
  loop:
  - C:\Temp
  - C:\Windows\Panther
  - C:\Windows\Temp

# win_file does not work with hidden folders
- name: cleanup the C:\Recovery folder
  win_shell: Remove-Item -Path C:\Recovery -Force -Recurse
  ignore_errors: yes

# we want to clear the folder contents and not the folder itself
- name: clear out the WinSXS ManifestCache folder
  win_shell: |
    &cmd.exe /c Takeown /f %windir%\winsxs\ManifestCache\*
    &cmd.exe /c Icacls %windir%\winsxs\ManifestCache\* /GRANT administrators:F
    &cmd.exe /c Del /q %windir%\winsxs\ManifestCache\*

- name: see if Optimize-Volume cmdlet is available
  win_command: powershell.exe "Get-Command -Name Optimize-Volume"
  register: pri_cleanup_defrag_cmdlet
  failed_when: False

- name: defrag C with PS cmdlet
  win_command: powershell.exe "Optimize-Volume -DriveLetter C"
  when: pri_cleanup_defrag_cmdlet.rc == 0

- name: defrag C with legacy exe
  win_command: 'Defrag.exe C:'
  when: pri_cleanup_defrag_cmdlet.rc != 0
