---
### Moved to the cleanup phase
# - name: run ngen to recompile .NET assemblies
#   win_dotnet_ngen:
#   tags:
#     ngen

- name: ensure unattend panther and temp directory exists
  win_file:
    path: '{{ item }}'
    state: directory
  loop:
  - C:\Windows\Panther\Unattend
  - C:\temp

- name: Make note for the template we ARE in sysprep phase
  set_fact:
    sysprep_phase: true

- name: Template the Sysprep unattend.xml file for checking later
  template:
    dest: "{{ man_host_type }}/sysprep-unattend.xml"
    src: "{{ playbook_dir }}/config/master-unattend.xml.j2"
  delegate_to: localhost

- name: Template the Sysprep unattend.xml file to OS
  win_template:
    src: "{{ playbook_dir }}/config/master-unattend.xml.j2"
    dest: C:\Windows\Panther\Unattend\unattend.xml

### Moved to the cleanup phase
# - name: set flag to recreate pagefile after next sysprep
#   win_shell: |
#     $system = Get-WmiObject -Class Win32_ComputerSystem -EnableAllPrivileges
#     if ($system -ne $null) {
#         $system.AutomaticManagedPagefile = $true
#         $system.Put()
#     }

### I dont think this is useful with "Thin" disks - if anything it can only force the hypervisor to actually allocate (another) disk space for zeros 
# - name: 0 out empty space for later compression
#   win_shell: |
#     $path = "C:\zero"
#     $volume = Get-WmiObject -Class Win32_LogicalDisk -Filter "DeviceID='C:'"
#     $block_size = 64kb
#     $leftover_size = $volume.Size * 0.05
#     $file_size = $volume.FreeSpace - $leftover_size
#     $data_array = New-Object -TypeName byte[]($block_size)
# 
#     $stream = [System.IO.File]::OpenWrite($path)
#     try {
#         $current_file_size = 0
#         while ($current_file_size -lt $file_size) {
#             $stream.Write($data_array, 0, $data_array.Length)
#             $current_file_size += $data_array.Length
#         }
#     } finally {
#         if ($stream) {
#             $stream.Close()
#         }
#     }
#     Remove-Item -Path $path -Force | Out-Null

- name: Run Sysprep which finishes the process (in VM mode)
  win_command: 'C:\windows\system32\sysprep\sysprep.exe /generalize /oobe /quiet /mode:vm /shutdown /unattend:C:\Windows\Panther\Unattend\unattend.xml'
  when: man_host_type != '2008r2'
 
- name: Run Sysprep which finishes the process
  win_command: 'C:\windows\system32\sysprep\sysprep.exe /generalize /oobe /quiet /shutdown /unattend:C:\Windows\Panther\Unattend\unattend.xml'
  when: man_host_type == '2008r2'
 
